UK_ROOT ?= $(PWD)/UNIK/unikraft
UK_LIBS ?= $(PWD)/UNIK/libs
LIBS := $(UK_LIBS)/musl

all:
	@$(MAKE) -C $(UK_ROOT) A=$(PWD) L=$(LIBS)

$(MAKECMDGOALS):
	@$(MAKE) -C $(UK_ROOT) A=$(PWD) L=$(LIBS) $(MAKECMDGOALS)
